version: "3"
services:
  promtail:
    image: "grafana/promtail:2.5.0"
    container_name: "promtail"
    restart: "always"
    network_mode: 'host'
    volumes:
      - "./:/mnt/config"
      - "/etc/localtime:/etc/localtime"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command:
      - "-config.file=/mnt/config/promtail-config.yaml"
